apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-practice-app
  namespace: argocd
spec:
  project: default # âœ… í•„ìˆ˜ í•­ëª© ì¶”ê°€
  source:
    repoURL: "https://github.com/EeyoungSong/kube-practice-infra.git" # ğŸ‘‰ Infra Repo ì£¼ì†Œ
    targetRevision: main
    path: k8s # ğŸ‘‰ YAMLì´ ìˆëŠ” í´ë” (ex: infra/k8s)
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
