apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: wu-app
data:
  DEBUG: "1"
  DJANGO_SETTINGS_MODULE: "config.settings"
  ENV: "production"
  ALLOWED_HOSTS: "api.word-universe.win,4.230.112.41,localhost,127.0.0.1"
