apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-practice-api
  labels:
    app: kube-practice-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-practice-api
  template:
    metadata:
      labels:
        app: kube-practice-api
    spec:
      containers:
        - name: kube-practice-api
          image: eeyoungacr.azurecr.io/kube-practice-api:7a3b097cedb0edc031babeec8e8d73433b83a1ab
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "production"
