apiVersion: v1
kind: Service
metadata:
  name: kube-practice-api-service
  labels:
    app: kube-practice-api
spec:
  selector:
    app: kube-practice-api # ✅ Deployment의 labels와 반드시 일치해야 합니다
  ports:
    - protocol: TCP
      port: 5000 # ✅ nginx.conf의 proxy_pass 포트
      targetPort: 5000 # ✅ 컨테이너 내부 포트
  type: ClusterIP # ✅ 내부 전용 (외부로는 안 나감)
