apiVersion: apps/v1
kind: Deployment
metadata:
  name: wu-be-app
  namespace: wu-app
  labels:
    app: wu-be-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wu-be-app
  template:
    metadata:
      labels:
        app: wu-be-app
    spec:
      containers:
        - name: wu-be-app
          image: eeyoungacr.azurecr.io/wu-be-app:bd150c0e9c0672a3f211205cd3f2d26f930020a0
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DEBUG

            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DJANGO_SETTINGS_MODULE

            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: ENV

            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: ALLOWED_HOSTS
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: OPENAI_API_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
